### PR TITLE
cards made

### PR DESCRIPTION
**Pull request by shelobel**
members cards made, colour scheme yet to be changed

### CODE REVIEW

**Comment by sa-y-an** [comment]
- The changes are required on the members' page https://ieee-deis.netlify.app/members and not on the home page 
- There is no year-wise segregation 
- Fix the padding 
- Content is not centralized 

I had asked to make it like the alumni page of IEEE SB site

**Review by sa-y-an — CHANGES_REQUESTED** [review]
Redo the PR on members page with 
- a data.js to load data
- year wise segregation 

Should have the functionality of https://www.ieeesbnitdgp.com/alumni

**Comment by shelobel** [comment]
where is the navigation for a different member's page? in this repository, the members section is nothing but a scrolled down section in the same page.

**Comment by sa-y-an** [comment]
> where is the navigation for a different member's page? in this repository, the members section is nothing but a scrolled down section in the same page.

- Yes there isn't
- Your task was to create one :)
@shelobel

**Comment by sa-y-an** [comment]
solved by #16

**Pull request closed without merging**
